### ISSUE TITLE
Несоответствие типов данных

### ISSUE THREAD

**Issue by grkhr** [selesnow/rym#1]
Вчера утром Яндекс (что Директ, что Метрика) начал частично отдавать столбцы визитов/отказов/кликов итд типом Float и куча ежедневных подгрузок в БД выдали ошибку следующего вида: "Field Visits has changed type from INTEGER to FLOAT [invalid]". Было бы клево подпереть костылём это в пакетах.

**Comment by selesnow** [comment]
Принял, спасибо за инфу, постараюсь в ближайшее время это проверить и доработать оба пакета.

**Comment by falkonua** [comment]
Приветствую.
У меня в метрике есть 63 цели, поскажите как можно получить статистику по количеству достижений каждой цели?

**Comment by selesnow** [comment]
Такие вещи сложновато отслеживать, поэтому пока тикет закрываю в ближайшее время точно заниматься этим не буду, не вижу проблемы после получения данных привести их в нужных вид. 

Сделать это как то универсально будет сложно.
