### ISSUE TITLE
Статистика по дням

### ISSUE THREAD

**Issue by arina-kaa** [selesnow/rym#3]
Приветствую!

Было бы здорово иметь возможность выгружать статистику по затратам на рекламу по дням.
API отчетов v1 поддерживает данную возможность:
https://yandex.ru/dev/metrika/doc/api2/api_v1/bytime-docpage/

**Comment by selesnow** [comment]
Здравствуйте, так вам достаточно добавить нужные поля в группировки, т.е. в аргумент `dimensions` одно из полей должно быть `ym:s:date` .

Или я не правильно понял ваш вопрос.

**Comment by selesnow** [comment]
Закрываю тикет т.к. не понимаю проблемы.
