### ISSUE TITLE
RYM_GET_DATA ошибка вектора? в metrics

### ISSUE THREAD

**Issue by Axeler8** [selesnow/rym#4]
В случае, когда показатели и параметры передаются через переменную, 
аргумент metrics  принимает только вектор длины 1, вот с такой ошибкой:

_Ошибка в vapply(elements, encode, character(1)) :
  значения должны иметь длину 1,
 но результат FUN(X[[2]]) имеет длину 4_

Сейчас для работы переменную с параметрами соединяем через paste(collapse = ',').

**Comment by Axeler8** [comment]
Аналогично с аргумнтом
counters

**Comment by selesnow** [comment]
Спасибо, внёс в пакет все описанные поправки, и ещё некоторые доработки. 
Можете переустанавливать пакет из gothub.
Все доработки внёс в файл https://github.com/selesnow/rym/blob/master/NEWS.md
